export const GET_ACTIVE_PARAGRAPH = "GET_ACTIVE_PARAGRAPH";
export const GET_ALL_RESULTS = "GET_ALL_RESULTS";
export const SET_ACTIVE_PARAGRAPH = "SET_ACTIVE_PARAGRAPH";
export const SET_TYPING_TEST_RESULTS = "SET_TYPING_TEST_RESULTS";
export const DELETE_RESULT = "DELETE_RESULT";